apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: logging
data:
  CLOUD_ELASTICSEARCH_PASSWORD: LyTtoxNuQJTA99njdThK7XKz
  CLOUD_ELASTICSEARCH_USER: elastic
type: Opaque
